---
title: Your awesome title
timezone: UTC
collections:
  authors:
    title: Authors
    output: true
    Main info:
      Bio: 
      Profile Image: 
    List some info:
    - - List one a
      - List one b
    - - List two a
      - List two b
      - List two c
    Two col with icons:
      Key:
      - First icon image: 
        First text content: 
      - Second icon image: 
        Second text content: 
  component-single-paragraph-with-icons:
    title: Component single paragraph with icon
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  component-hero-videos:
    title: component-hero-video
    output: false
  stood:
    title: stood
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
<<<<<<< HEAD
    skeleton:
      nav-image:
=======
    skeleton: 
>>>>>>> 320bed3b32bee51134465285b6597cc8535eab67
- scope:
    path: ''
    type: component-single-paragraph-with-icons
  values:
    elements:
      icon image:
      paragraph text:
- scope:
    path: ''
    type: authors
  values:
    permalink: "/blog/authors/:title/"
    layout: author
    twitter: 
    facebook: 
- scope:
    path: ''
    type: posts
  values:
    permalink: "/blog/:title/"
    layout: post
    author: 
email: your-email@example.com
description: Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for Google search
  results) and in your feed.xml site description.
baseurl: 
url: http://localhost:4000/
twitter_username: jekyllrb
github_username: dorianwolf
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
